# docker compose -f compose-opensearch.yml up opensearch
# docker compose -f compose-opensearch.yml up opensearch-dashboards

name: opensearch

networks:
  opensearch-network:
    name: opensearch-network
    driver: bridge

volumes:
  opensearch-data:
    name: opensearch-data

services:
  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:2.19.3
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    volumes:
      - opensearch-data:/usr/share/opensearch/data
      # config file
      # - ./opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    networks:
      - opensearch-network
    # https://www.elastic.co/docs/deploy-manage/deploy/self-managed/install-elasticsearch-docker-basic#_start_a_single_node_cluster
    mem_limit: 2g

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.19.3
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    # volumes:
      # config file
      # - ./opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"] # Define the OpenSearch nodes that OpenSearch Dashboards will query
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    networks:
      - opensearch-network
    depends_on:
      - opensearch
